version: '2'

services:
   db:
     image: mysql:5.7
     container_name: prosody_mysql
     volumes:
       - ./prosody_db_data:/var/lib/mysql

       # Only use this line for the initial start up (the very first time docker-compose is run
       # With this line uncommented, the database will be overwritten using the .sql file
       #- ./initial_sql/prosody_production.sql:/docker-entrypoint-initdb.d/prosody_production.sql
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
       MYSQL_DATABASE: ${MYSQL_DATABASE}
       MYSQL_USER: ${MYSQL_USER}
       MYSQL_PASSWORD: ${MYSQL_PASSWORD}
     labels:
       - "traefik.enable=false"

   wordpress:
     build:
       context: .
     depends_on:
       - db
     image: prosody_wp:0.1
     volumes:
       - ./wp-custom-bulk-actions:/var/www/html/wp-content/plugins/custom-bulk-actions/
       - ./prosody_plugin:/var/www/html/wp-content/plugins/prosody_plugin/
       - ./prosody_theme:/var/www/html/wp-content/themes/prosody/
       - ./uploads:/var/www/html/wp-content/uploads/
     restart: always
     environment:
       WORDPRESS_DB_HOST: ${WORDPRESS_DB_HOST}
       WORDPRESS_DB_USER: ${MYSQL_USER}
       WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}
       WORDPRESS_TABLE_PREFIX: ${WORDPRESS_TABLE_PREFIX}
     expose:
       - "80"
     labels:
       - "traefik.enable=true"
       - "traefik.docker.network=thenetwork"
       - "traefik.port=80"
       - "traefik.backend=prosody_wordpress"
       - "traefik.frontend.rule=Host:prosody.lib.virginia.edu"

networks:
  default:
    external:
      name: thenetwork
