java -jar saxon8.jar   -s  '../poems/Anon - Westron Wynde.xml' batch.xsl > '../poems2/Anon - Westron Wynde.xml'
java -jar saxon8.jar   -s  '../poems/Author - Title.xml' batch.xsl > '../poems2/Author - Title.xml'
java -jar saxon8.jar   -s  '../poems/Carroll - Jabberwocky.xml' batch.xsl > '../poems2/Carroll - Jabberwocky.xml'
java -jar saxon8.jar   -s  '../poems/Drayton - 61.xml' batch.xsl > '../poems2/Drayton - 61.xml'
java -jar saxon8.jar   -s  '../poems/Frost - In Neglect.xml' batch.xsl > '../poems2/Frost - In Neglect.xml'
java -jar saxon8.jar   -s  '../poems/Frost - Mowing.xml' batch.xsl > '../poems2/Frost - Mowing.xml'
java -jar saxon8.jar   -s  '../poems/Hardy - I Look Into My Glass.xml' batch.xsl > '../poems2/Hardy - I Look Into My Glass.xml'
java -jar saxon8.jar   -s  '../poems/Hardy - The Oxen.xml' batch.xsl > '../poems2/Hardy - The Oxen.xml'
java -jar saxon8.jar   -s  '../poems/Herrick - Upon Julias Clothes.xml' batch.xsl > '../poems2/Herrick - Upon Julias Clothes.xml'
java -jar saxon8.jar   -s  '../poems/Hopkins - Gods Grandeur.xml' batch.xsl > '../poems2/Hopkins - Gods Grandeur.xml'
java -jar saxon8.jar   -s  '../poems/Hopkins - Heaven-Haven - A Nun Takes the Veil.xml' batch.xsl > '../poems2/Hopkins - Heaven-Haven - A Nun Takes the Veil.xml'
java -jar saxon8.jar   -s  '../poems/Houseman - The Night is Freazing Fast2.xml' batch.xsl > '../poems2/Houseman - The Night is Freazing Fast2.xml'
java -jar saxon8.jar   -s  '../poems/Keats - Bright Star.xml' batch.xsl > '../poems2/Keats - Bright Star.xml'
java -jar saxon8.jar   -s  '../poems/Landor - Dying Speech of an Old Philosopher.xml' batch.xsl > '../poems2/Landor - Dying Speech of an Old Philosopher.xml'
java -jar saxon8.jar   -s  '../poems/Poet - Title.xml' batch.xsl > '../poems2/Poet - Title.xml'
java -jar saxon8.jar   -s  '../poems/Pope - Essay on Criticism ll. 362-73.xml' batch.xsl > '../poems2/Pope - Essay on Criticism ll. 362-73.xml'
java -jar saxon8.jar   -s  '../poems/Rossetti - Echo.xml' batch.xsl > '../poems2/Rossetti - Echo.xml'
java -jar saxon8.jar   -s  '../poems/Rossetti - The Lowest Place.xml' batch.xsl > '../poems2/Rossetti - The Lowest Place.xml'
java -jar saxon8.jar   -s  '../poems/Shakespeare - 18.xml' batch.xsl > '../poems2/Shakespeare - 18.xml'
java -jar saxon8.jar   -s  '../poems/Shakespeare - 29.xml' batch.xsl > '../poems2/Shakespeare - 29.xml'
java -jar saxon8.jar   -s  '../poems/Shakespeare - 73.xml' batch.xsl > '../poems2/Shakespeare - 73.xml'
java -jar saxon8.jar   -s  '../poems/Shelley - Mont Blanc 1-11.xml' batch.xsl > '../poems2/Shelley - Mont Blanc 1-11.xml'
java -jar saxon8.jar   -s  '../poems/Shelley - Mont Blanc ll. 1-11.xml' batch.xsl > '../poems2/Shelley - Mont Blanc ll. 1-11.xml'
java -jar saxon8.jar   -s  '../poems/Sidney - 31.xml' batch.xsl > '../poems2/Sidney - 31.xml'
java -jar saxon8.jar   -s  '../poems/Wordsworth - A Slumber Did My Spirit Seal.xml' batch.xsl > '../poems2/Wordsworth - A Slumber Did My Spirit Seal.xml'
java -jar saxon8.jar   -s  '../poems/Wordsworth - A Sonnet.xml' batch.xsl > '../poems2/Wordsworth - A Sonnet.xml'
java -jar saxon8.jar   -s  '../poems/Yeats - He Wishes for the Cloths of Heaven.xml' batch.xsl > '../poems2/Yeats - He Wishes for the Cloths of Heaven.xml'
java -jar saxon8.jar   -s  '../poems/Yeats - The Cold Heaven.xml' batch.xsl > '../poems2/Yeats - The Cold Heaven.xml'
java -jar saxon8.jar   -s  '../poems/test.xml' batch.xsl > '../poems2/test.xml'

